/**
 * generate-logos — 把 `src/client/assets/logos/` 下的厂商 logo 图片转成
 * base64 data URL，生成 `src/client/brand-logos.generated.ts`。
 *
 * 用法（在插件目录）：node scripts/generate-logos.mjs
 *
 * 命名规范：文件名（小写，去扩展名）即品牌 key，必须与
 * `src/client/RoundTableView.tsx` 中 PROVIDER_BRAND 的 `key` 对应：
 *   deepseek / glm / openai / claude / qwen / kimi / gemini / minimax
 * 支持 .png / .svg / .jpg / .jpeg / .webp。
 *
 * 生成文件是派生物，勿手改；换图后重跑本脚本再构建即可。
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { extname, join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const LOGO_DIR = join(ROOT, 'src', 'client', 'assets', 'logos')
const OUT_FILE = join(ROOT, 'src', 'client', 'brand-logos.generated.ts')

const MIME = {
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
}

let entries = []
try {
  entries = await readdir(LOGO_DIR, { withFileTypes: true })
} catch {
  // 目录不存在：生成空表，构建仍可用（回退到缩写头像）。
}

const logos = {}
for (const entry of entries) {
  if (!entry.isFile()) continue
  const ext = extname(entry.name).toLowerCase()
  const mime = MIME[ext]
  if (mime === undefined) continue
  const key = entry.name.slice(0, -ext.length).toLowerCase()
  if (key === '') continue
  const data = await readFile(join(LOGO_DIR, entry.name))
  logos[key] = `data:${mime};base64,${data.toString('base64')}`
}

const keys = Object.keys(logos)
const body = keys
  .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(logos[key])},`)
  .join('\n')

await mkdir(dirname(OUT_FILE), { recursive: true })
await writeFile(OUT_FILE, [
  '/**',
  ' * AUTO-GENERATED by scripts/generate-logos.mjs — do not edit by hand.',
  ' * 图片源：src/client/assets/logos/（见该脚本头部的命名规范）。',
  ' */',
  `export const BRAND_LOGOS: Record<string, string> = {`,
  body,
  `}`,
  '',
].join('\n'), 'utf8')

console.log(`[generate-logos] ${keys.length} logo(s) -> ${OUT_FILE}`)
for (const key of keys) console.log(`  - ${key}: ${logos[key].slice(0, 40)}… (${logos[key].length} chars)`)
